---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ilink-gateway
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./specs/stage/web/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: ilink
  validation: client
