apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ilink-youthink
  namespace: istio-system
spec:
  secretName: kratos-ilink-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'identity.ilink.pw'
  dnsNames:
    - 'identity.ilink.pw'
