---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: db-operator
      sourceRef:
        kind: HelmRepository
        name: db-operator
      version: 0.5.1
  interval: 1h0m0s
  targetNamespace: default
