---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: db
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.1.1
  interval: 1h0m0s
  releaseName: db
  targetNamespace: default
  values:
    postgresqlDatabase: default
    postgresqlUsername: postgres
    postgresqlPassword: password