apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: github-credentials
    template:
      type: Opaque
      data:
        username: "ilink-bot"
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: github-token
