apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ilink-private-gateway
  namespace: flux-system
spec:
  image: eu.gcr.io/task-monit-1599295644751/ilink-gateway-private-gateway-entrypoint
  interval: 1m0s
