apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ilink-accounts
  namespace: flux-system
spec:
  image: eu.gcr.io/task-monit-1599295644751/ilink-accounts-app-entrypoint
  interval: 1m0s
