apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ilink-accounts
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ilink-accounts
  filterTags:
    pattern: '^[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
